server:
  port: 9015
  error:
    include-message: always

spring:
  application:
    name: demo-microservice
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


Feing:
  hystrix:
    enabled: true
managment:
  endpoints:
    web:
      exposure:
        include: *
    
