
spring:
  datasource:
    url: jdbc:sqlserver://localhost:61006;databaseName=HelpDesk
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: live550e60
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        dll:
          auto: update
        format:
          sql: true
      show:
        sql: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defeaultZone: http://localhost:8099/eureka/

