server:
  port: 9015
  error:
    include-message: always

spring:
  application:
    name: demo-microservice
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka
    
