server:
  port: 9020
  error:
    include-message: always

spring:
  application:
    name: demo-microservice
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defeaultZone: http://localhost:8099/eureka/
    
