server:
  port: 8099

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8099/eureka/