server:
  port: 8099

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/